name: Cypress Tests #nombre del workflow

on: # eventos que activan el workflow
  push:
    branches: # ramas en las que se ejecutar치 este workflow al hacer push
      - main
      - develop
      - feat/**
  pull_request:
    branches:
      - main

jobs: # define el workflow y las configuraciones
  cypress-run:
    runs-on: ubuntu-latest # m치quina virtual ubuntu como entorno

    defaults: # Define que todos los comandos se ejecuten dentro de la carpeta cypress-tests (el nombre que se le dio a la carpeta)
      run:
        working-directory: cypress-tests

    env: # variables de entorno disponibles para el job completo
      CYPRESS_BASE_URL: https://mk-havana.vercel.app/ # url base para las pruebas
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # clave secreta para Cypress Cloud
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # token para integraciones y permisos

    steps: # pasos que se ejecutan en este job
      - name: Checkout c칩digo
        uses: actions/checkout@v4 # clona el repositorio en la m치quina virtual

      - name: Cypress run (Cypress Cloud)
        uses: cypress-io/github-action@v6 # corre los tests
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Cypress tests
        run: npm test

      - name: Subir videos/screenshots si fallan
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress-tests/cypress/videos
            cypress-tests/cypress/screenshots
